### ISSUE TITLE
Missing go.sum

### ISSUE THREAD

**Issue by rafal06** [zapomnij/gtkLauncher#1]
When trying to compile it, Go complains about missing packages from go.sum, which is gitignored

![image](https://github.com/zapomnij/gtkLauncher/assets/70489677/e7f67db2-4a21-4991-9d9d-bd94108bf751)

**Comment by zapomnij** [comment]
Fixed since [29bbcbf](https://github.com/zapomnij/gtkLauncher/commit/29bbcbf7ddaa2de31cd028b22dd18c00959450c4)
